# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_management.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user_management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15user_management.proto\x12\x0eusermanagement\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n\x0bUserProfile\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x11\n\tfirstName\x18\x02 \x01(\t\x12\x10\n\x08lastName\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12-\n\tcreatedAt\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tupdatedAt\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\";\n\x05Group\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\">\n\x11\x43reateUserRequest\x12)\n\x04user\x18\x01 \x01(\x0b\x32\x1b.usermanagement.UserProfile\"?\n\x12\x43reateUserResponse\x12)\n\x04user\x18\x01 \x01(\x0b\x32\x1b.usermanagement.UserProfile\" \n\x0eGetUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"<\n\x0fGetUserResponse\x12)\n\x04user\x18\x01 \x01(\x0b\x32\x1b.usermanagement.UserProfile\":\n\x12\x43reateGroupRequest\x12$\n\x05group\x18\x01 \x01(\x0b\x32\x15.usermanagement.Group\";\n\x13\x43reateGroupResponse\x12$\n\x05group\x18\x01 \x01(\x0b\x32\x15.usermanagement.Group\"\"\n\x0fGetGroupRequest\x12\x0f\n\x07groupId\x18\x01 \x01(\t\"8\n\x10GetGroupResponse\x12$\n\x05group\x18\x01 \x01(\x0b\x32\x15.usermanagement.Group2\xd8\x02\n\x0eUserManagement\x12S\n\nCreateUser\x12!.usermanagement.CreateUserRequest\x1a\".usermanagement.CreateUserResponse\x12J\n\x07GetUser\x12\x1e.usermanagement.GetUserRequest\x1a\x1f.usermanagement.GetUserResponse\x12V\n\x0b\x43reateGroup\x12\".usermanagement.CreateGroupRequest\x1a#.usermanagement.CreateGroupResponse\x12M\n\x08GetGroup\x12\x1f.usermanagement.GetGroupRequest\x1a .usermanagement.GetGroupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERPROFILE']._serialized_start=75
  _globals['_USERPROFILE']._serialized_end=250
  _globals['_GROUP']._serialized_start=252
  _globals['_GROUP']._serialized_end=311
  _globals['_CREATEUSERREQUEST']._serialized_start=313
  _globals['_CREATEUSERREQUEST']._serialized_end=375
  _globals['_CREATEUSERRESPONSE']._serialized_start=377
  _globals['_CREATEUSERRESPONSE']._serialized_end=440
  _globals['_GETUSERREQUEST']._serialized_start=442
  _globals['_GETUSERREQUEST']._serialized_end=474
  _globals['_GETUSERRESPONSE']._serialized_start=476
  _globals['_GETUSERRESPONSE']._serialized_end=536
  _globals['_CREATEGROUPREQUEST']._serialized_start=538
  _globals['_CREATEGROUPREQUEST']._serialized_end=596
  _globals['_CREATEGROUPRESPONSE']._serialized_start=598
  _globals['_CREATEGROUPRESPONSE']._serialized_end=657
  _globals['_GETGROUPREQUEST']._serialized_start=659
  _globals['_GETGROUPREQUEST']._serialized_end=693
  _globals['_GETGROUPRESPONSE']._serialized_start=695
  _globals['_GETGROUPRESPONSE']._serialized_end=751
  _globals['_USERMANAGEMENT']._serialized_start=754
  _globals['_USERMANAGEMENT']._serialized_end=1098
# @@protoc_insertion_point(module_scope)
